language: ruby
rvm:
  # RubyInstallerで提供される最新版を、指定・利用の目安としている
  - 2.3.1
before_script:
  - chmod +x ./script/cibuild
script: ./script/cibuild
after_script: "find _site -type f"
sudo: false
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
cache: bundler

